### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by ghost** [PGSSoft/HashId#3]
Hello,

I'm using symfony 5.0. When copying your configuration (pgs_hash_id.yaml) i get this error "Unrecognize options " salut,min_lenght,alphabet" under pgs_hash_id. Available option is converter".  I changed the configuration passing by concerter: hashids then options.

And after that nothing is working. Thanks for your help

**Comment by kjonski** [comment]
Hello,
Thank you for your input. There are pull request with updates in documentation of configuration to meet current structure. Please check it if possible.

Regards,
Karol

**Comment by ghost** [comment]
Hello dear,
Thanks but i'm not familiar to github. Please can you tell me why the
PGSSoft/Hashids after configuration does no effect. No id is hashed.

Regards,
Josaphat

**Comment by kjonski** [comment]
Hello,
PGSSoft/Hashids comes with default configuration and for initial usage changes in configuration are not required - but recommended to have "own" hashes.
If you still have configuration structure issues than your `config/packages/pgs_hash_id.yaml` file should looks like this:
```
pgs_hash_id:
  converter:
    hashids:
      salt: 'my super salt'
      min_hash_length: 20
      alphabet: 'qwertyasdzxc098765-'
```
Necessary thing is to add `@Hash` annotation over your controller action for which you want to hash id (more parameter(s) than id) - no url parameters are hashed without annotation.
Please follow [Controller configuration](https://github.com/PGSSoft/HashId#controller-configuration) section.

Please let me know if you will have more questions.

Regards,
Karol

**Comment by ghost** [comment]
Hello,
I have already imported the Hash as you can see in the attached file but
sometimes no error  and other times i get an error when calling
decodeControllerParameter.

Thanks for your help.

**Comment by ghost** [comment]
But the hotel parameter is still not hashed. I tried even to replace the
Hotel object by int but nothing worked.

Thanks

Le vendredi 24 avril 2020, Josaphat Imani <josaphat.imani97@gmail.com> a
écrit :

> Hello,
> I have already imported the Hash as you can see in the attached file but
> sometimes no error  and other times i get an error when calling
> decodeControllerParameter.
>
> Thanks for your help.
>

**Comment by ghost** [comment]
Hello. I'm getting this error: "only arrays and traversables can be unpacked" in service/DecodeControllerParameter.php line 28. What can be the problem be cause i breaks all pages ? To make pages work i commented the bundle in config/bundles.php and pgs_hash_id.yaml, reload the page then uncomment them again

**Comment by kjonski** [comment]
Hallo,
I can't see any attachment in your previous comments :( but I have impression that you are trying to use code in wrong as there is no need to call `decodeControllerParameter` directly as it is done under the hood.
Did you configure `Hash` annotation in your controller?
Maybe you are able to share your code in repository or gist and we can check it together?

**Comment by ghost** [comment]
Please i answered via gmail and sent an attachment reason why. I did not
call the decodeControllerParameter in my code. The error is thrown by
symfony. I used code like it is explained in documentation ie Hash and just
configuration. Thanks

**Comment by kjonski** [comment]
Hello!
I found what is the problem and working solution for new issue #7

**Comment by ghost** [comment]
Thanks. I'm just waiting for it.

**Comment by kjonski** [comment]
One more question - do you use any param converter (like Doctrine Param Converter) or anything similar (and what if yes)?  
Regards,
Karol

**Comment by ghost** [comment]
Yes i use doctrine param converter but i also tried to use without it and
the error still thrown.

**Comment by kjonski** [comment]
Hello!
There is newest version o branch 3.0 (tag v3.0.2) with current and #7 hopefully resolved.
Hope it will work now for you.

Regards,
Karol

**Comment by kjonski** [comment]
Hello @Ji97!
Was you able to check fix for issue?

Regards,
Karol

**Comment by ghost** [comment]
Hello. I had a problem with composer and i fixed it yesterday. I will try
PGS tomorrow in morning. Thanks.

**Comment by ghost** [comment]
Hello. I tested v3.0.2 with this result : error in
decodeControllerParameter is not thrown but the ids couldn't be hashed.

Le mercredi 6 mai 2020, Josaphat Imani <josaphat.imani97@gmail.com> a
écrit :

> Hello. I had a problem with composer and i fixed it yesterday. I will try
> PGS tomorrow in morning. Thanks.
>

**Comment by kjonski** [comment]
Hello!
I checked bundle with latest Symfony (5.0.7) both with and without Doctrine Param Converter and was able to successfully encode and decode parameters. Are you sure that you parameters names matches (method declaration and Hash annotation)?
```
    /**
     * @Route("sand/demo_pc/{note}", name="demo_pc")
     * @Hash("note")
     * @ParamConverter("note", class="Note")
     * @param Request $request
     * @param Note    $note
     *
     * @return Response
     */
    public function demoParamConverterAction(Request $request, Note $note)
    {
        return new Response($note->getId());
    }
```

**Comment by ghost** [comment]
Hello,

I see what was the matter. I didn't use the param converter explicitly.
Note that the @ParamConverter annotation is missing.

    /**
     * @Route("sand/demo_pc/{note}", name="demo_pc")
     * @Hash("note")
     * @param Request $request
     * @param Note    $note
     *
     * @return Response
     */
    public function demoParamConverterAction(Request $request, Note $note)
    {
        return new Response($note->getId());
    }

**Comment by kjonski** [comment]
Hello Josaphat!
Was you able encode desired parameters in the end? Or do you need any support?

Regards,
Karol

**Comment by ghost** [comment]
Hello,

I'm still having unhashed ids. Here is my code

In Controller

use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Pgs\HashIdBundle\Annotation\Hash;

/**
 * @Route({
 * "en": "/show-{hotel}",
 * "fr": "/explorer-{hotel}"
 * }, name="hotel_show", methods={"GET"})
 *
 * @Hash("hotel")
 * @ParamConverter("hotel", class="App\Entity\Hotel\Hotel")
 *
 */
public function show(EntityManagerInterface $em, Hotel $hotel)
{
}

In pgs_hash_id.yaml

pgs_hash_id:
  converter:
    hashids:
      salt: 'josaphat'
      min_hash_length: 13
      alphabet: '0123456789abcdefghijklmnopqrstuvwxyz'

After many tries I noticed that the @ParamConverter has effect if i enter
an undefined param which is not the case with @Hash.

No error is throwing and the @ParamConverter still doing his job as
expected but the id is not hashed.

Thanks for a help.

**Comment by kjonski** [comment]
Hello Josaphat!
I prepared repository with some tests for hashid bundle integration - for this moment only SF 5.0.7. Please follow example related to yours under [https://github.com/kjonski/pgs-hashid-bundle-test/blob/symfony507-paramconverter/src/Controller/SandController.php#L39](https://github.com/kjonski/pgs-hashid-bundle-test/blob/symfony507-paramconverter/src/Controller/SandController.php#L39)

Regards,
Karol

**Comment by ghost** [comment]
Hello,

I got it work.
But there must be some adjustments for supporting internationalized routes
in Pgs\HashIdBundle\Decorator\RouterDecorator.php line 36

$route = $this->getRouter()->getRouteCollection()->get($name);

Internationalized routes have names like "hotel_show.en" and "hotel_show.fr"
while here  $name has value "hotel_show".

Waiting for the changes. Thanks. It's a beautyful bundle by the way.

**Comment by kjonski** [comment]
Hello,
Thank you for your positive feedback. Now I can see your problem.
As it is not related to documentation itself I opened new issue #9 and I'll close current.

Regards,
Karol

**Comment by ghost** [comment]
Thanks you too. Just waiting for changes because all of my routes are
internationalized.

**Comment by kjonski** [comment]
Hello!
There is v3.0.3 published with support for internationalized routes. Hope it will match your needs :)

**Comment by ghost** [comment]
Hello,

The v3.0.3 works perfectly but i'm facing an issue with twig code that make
the locale modification possible.

{% for locale in app_locales %}
    <a href="{{ path(app.request.get('_route'),
app.request.get('_route_params')|merge({'lang': locale})) }}">
        {{ locale|trans }}
    </a>
{% endfor %}

Error thrown is An exception has been thrown during the rendering of a
template ("Parameter "hotel" for route "hotel_show.en" must match "[^/]++"
("" given) to generate a corresponding URL.").

**Comment by kjonski** [comment]
Hello after long break!
I added some twig based examples to bundle testing [repository](https://github.com/kjonski/pgs-hashid-bundle-test/blob/symfony507-paramconverter/templates/internationalized.html.twig) so you can follow examples. 

Regards,
Karol

**Comment by ghost** [comment]
Hello dear,

Thanks for examples. I personnaly have a base.html independant of hotel
entity where i have twig code for that change the locale. And it throws
error when opening url hotel_show. But if i remove internalization for that
route everything works fine.

Thank you.
